import type { PlatformItem } from "./platforms";

export const platformsVi: PlatformItem[] = [
  {
    key: "facebook",
    name: "Facebook",
    description: "Hỗ trợ tăng trưởng cho trang, hồ sơ và nội dung.",
    longDescription: "Tăng like trang, follow, tương tác bài viết, view video và cảm xúc Facebook từ một dashboard duy nhất. Facebook vẫn là một trong những nền tảng phổ biến nhất cho doanh nghiệp và cộng đồng.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#1877F2",
    keywords: [
      { title: "Tăng Like Fanpage", description: "Tăng lượng người theo dõi cho trang." },
      { title: "Tăng Followers", description: "Tăng số người theo dõi Facebook." },
      { title: "Tăng View Video", description: "Tăng lượt xem video Facebook." },
      { title: "Tăng Reactions", description: "Đa dạng cảm xúc: Love, Haha, Wow." },
      { title: "Tăng Shares", description: "Tăng lượt chia sẻ bài viết." },
    ],
  },
  {
    key: "instagram",
    name: "Instagram",
    description: "Hỗ trợ tăng trưởng cho hồ sơ, bài đăng và reels.",
    longDescription: "Tăng followers, like, view và tương tác Instagram cho hồ sơ, bài đăng, reels và story từ một dashboard.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#E1306C",
    keywords: [
      { title: "Tăng Followers", description: "Tăng lượng người theo dõi Instagram." },
      { title: "Tăng Like Bài Viết", description: "Tăng lượt thích cho ảnh và video." },
      { title: "Tăng View Reels", description: "Tăng lượt xem cho video ngắn." },
      { title: "Tăng View Story", description: "Tăng lượt xem story của bạn." },
      { title: "Tăng Comments", description: "Thêm bình luận cho bài đăng." },
    ],
  },
  {
    key: "tiktok",
    name: "TikTok",
    description: "Hỗ trợ tăng trưởng cho kênh và nội dung video ngắn.",
    longDescription: "Tăng followers, like, view và mắt live TikTok để đẩy video lên xu hướng và tăng độ phủ nội dung nhanh chóng.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#25F4EE",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi kênh TikTok." },
      { title: "Tăng Like Video", description: "Tăng lượt tim cho video." },
      { title: "Tăng View Video", description: "Tăng lượt xem cho nội dung." },
      { title: "Tăng Mắt Live", description: "Tăng người xem livestream." },
      { title: "Tăng Shares", description: "Tăng lượt chia sẻ video." },
    ],
  },
  {
    key: "youtube",
    name: "YouTube",
    description: "Hỗ trợ tăng trưởng cho kênh và nội dung video dài.",
    longDescription: "Tăng subscribers, view, like và giờ xem YouTube để phát triển kênh và mở khoá các tính năng kiếm tiền.",
    services: ["Subscribers", "Views", "Likes"],
    accent: "#FF0000",
    keywords: [
      { title: "Tăng Subscribers", description: "Tăng người đăng ký kênh." },
      { title: "Tăng View Video", description: "Tăng lượt xem video YouTube." },
      { title: "Tăng Like", description: "Tăng lượt thích cho video." },
      { title: "Tăng Watch Hours", description: "Tăng giờ xem để đủ điều kiện kiếm tiền." },
      { title: "Tăng Comments", description: "Thêm bình luận cho video." },
    ],
  },
  {
    key: "telegram",
    name: "Telegram",
    description: "Hỗ trợ tăng trưởng cho kênh và nhóm cộng đồng.",
    longDescription: "Tăng members, view và reactions Telegram cho kênh và nhóm cộng đồng của bạn một cách ổn định.",
    services: ["Members", "Views", "Reactions"],
    accent: "#26A5E4",
    keywords: [
      { title: "Tăng Members Kênh", description: "Tăng thành viên cho kênh Telegram." },
      { title: "Tăng Members Group", description: "Tăng thành viên cho nhóm chat." },
      { title: "Tăng View Bài Viết", description: "Tăng lượt xem cho bài đăng." },
      { title: "Tăng Reactions", description: "Tăng cảm xúc cho bài viết." },
      { title: "Tăng Shares", description: "Tăng lượt chia sẻ bài viết." },
    ],
  },
  {
    key: "x",
    name: "X",
    description: "Hỗ trợ tăng trưởng cho hồ sơ và bài đăng.",
    longDescription: "Tăng followers, like, retweet và view X (Twitter) để mở rộng độ phủ bài viết và tăng uy tín hồ sơ.",
    services: ["Followers", "Likes", "Views"],
    accent: "#e7e9ea",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi X." },
      { title: "Tăng Like", description: "Tăng lượt thích cho tweet." },
      { title: "Tăng Retweet", description: "Tăng lượt đăng lại bài viết." },
      { title: "Tăng View", description: "Tăng lượt xem tweet." },
      { title: "Tăng Comments", description: "Tăng reply cho bài viết." },
    ],
  },
  {
    key: "threads",
    name: "Threads",
    description: "Hỗ trợ tăng trưởng cho hồ sơ và nội dung văn bản.",
    longDescription: "Tăng followers, like và view Threads để phát triển cộng đồng trên nền tảng mạng xã hội mới của Meta.",
    services: ["Followers", "Likes", "Views"],
    accent: "#e7e9ea",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi Threads." },
      { title: "Tăng Like", description: "Tăng lượt thích cho bài đăng." },
      { title: "Tăng View", description: "Tăng lượt xem nội dung." },
      { title: "Tăng Reply", description: "Tăng phản hồi cho bài viết." },
      { title: "Tăng Repost", description: "Tăng lượt đăng lại bài viết." },
    ],
  },
  {
    key: "spotify",
    name: "Spotify",
    description: "Hỗ trợ tăng trưởng cho nghệ sĩ, playlist và nội dung âm thanh.",
    longDescription: "Tăng plays, followers và playlist Spotify cho nghệ sĩ và nhà sáng tạo nội dung âm thanh.",
    services: ["Plays", "Followers", "Playlist"],
    accent: "#1DB954",
    keywords: [
      { title: "Tăng Plays", description: "Tăng lượt nghe cho bài hát." },
      { title: "Tăng Followers", description: "Tăng người theo dõi nghệ sĩ." },
      { title: "Tăng Playlist", description: "Thêm bài hát vào playlist." },
      { title: "Tăng Monthly Listeners", description: "Tăng người nghe hàng tháng." },
      { title: "Tăng Saves", description: "Tăng lượt lưu bài hát." },
    ],
  },
  {
    key: "linkedin",
    name: "LinkedIn",
    description: "Hỗ trợ tăng trưởng cho hồ sơ cá nhân và trang công ty.",
    longDescription: "Tăng followers, like, comment và view LinkedIn cho hồ sơ cá nhân, trang công ty và bài đăng chuyên nghiệp.",
    services: ["Followers", "Likes", "Views"],
    accent: "#0A66C2",
    keywords: [
      { title: "Tăng Followers Cá Nhân", description: "Tăng kết nối và người theo dõi hồ sơ." },
      { title: "Tăng Followers Công Ty", description: "Tăng người theo dõi trang công ty." },
      { title: "Tăng Like Bài Viết", description: "Tăng lượt thích cho bài đăng." },
      { title: "Tăng Comments", description: "Thêm bình luận cho bài viết." },
      { title: "Tăng View Hồ Sơ", description: "Tăng lượt xem profile." },
    ],
  },
  {
    key: "pinterest",
    name: "Pinterest",
    description: "Hỗ trợ tăng trưởng cho pin, board và hồ sơ.",
    longDescription: "Tăng followers, saves, views và click Pinterest cho pin, board và hồ sơ của bạn.",
    services: ["Followers", "Saves", "Views"],
    accent: "#E60023",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi Pinterest." },
      { title: "Tăng Saves Pin", description: "Tăng lượt lưu pin." },
      { title: "Tăng View Pin", description: "Tăng lượt xem pin." },
      { title: "Tăng Clicks", description: "Tăng lượt click vào pin." },
      { title: "Tăng Comments", description: "Tăng bình luận trên pin." },
    ],
  },
  {
    key: "snapchat",
    name: "Snapchat",
    description: "Hỗ trợ tăng trưởng cho hồ sơ, story và spotlight.",
    longDescription: "Tăng followers, views và engagement Snapchat cho hồ sơ cá nhân và nội dung spotlight.",
    services: ["Followers", "Views", "Engagement"],
    accent: "#FFFC00",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi Snapchat." },
      { title: "Tăng View Story", description: "Tăng lượt xem story." },
      { title: "Tăng View Spotlight", description: "Tăng lượt xem video spotlight." },
      { title: "Tăng Snap Score", description: "Tăng điểm hoạt động Snapchat." },
      { title: "Tăng Shares", description: "Tăng lượt chia sẻ story." },
    ],
  },
  {
    key: "reddit",
    name: "Reddit",
    description: "Hỗ trợ tăng trưởng cho subreddit và bài đăng.",
    longDescription: "Tăng members, upvotes, comments và view Reddit cho subreddit và bài đăng của bạn.",
    services: ["Members", "Upvotes", "Views"],
    accent: "#FF4500",
    keywords: [
      { title: "Tăng Members Subreddit", description: "Tăng thành viên cho cộng đồng." },
      { title: "Tăng Upvotes", description: "Tăng lượt upvote cho bài viết." },
      { title: "Tăng Comments", description: "Thêm bình luận cho post." },
      { title: "Tăng View Post", description: "Tăng lượt xem bài đăng." },
      { title: "Tăng Karma", description: "Tăng điểm karma cho tài khoản." },
    ],
  },
  {
    key: "discord",
    name: "Discord",
    description: "Hỗ trợ tăng trưởng cho server và cộng đồng.",
    longDescription: "Tăng members, reactions và online Discord cho server và cộng đồng của bạn.",
    services: ["Members", "Reactions", "Online"],
    accent: "#5865F2",
    keywords: [
      { title: "Tăng Members Server", description: "Tăng thành viên tham gia server." },
      { title: "Tăng Online", description: "Tăng số lượng người online." },
      { title: "Tăng Reactions", description: "Tăng lượt reaction cho tin nhắn." },
      { title: "Tăng Voice", description: "Tăng người trong voice chat." },
      { title: "Tăng Boosts", description: "Tăng lượt boost cho server." },
    ],
  },
  {
    key: "twitch",
    name: "Twitch",
    description: "Hỗ trợ tăng trưởng cho kênh và livestream.",
    longDescription: "Tăng followers, view và chat engagement Twitch cho kênh và buổi livestream của bạn.",
    services: ["Followers", "Views", "Engagement"],
    accent: "#9146FF",
    keywords: [
      { title: "Tăng Followers", description: "Tăng người theo dõi kênh Twitch." },
      { title: "Tăng Live Viewers", description: "Tăng người xem livestream." },
      { title: "Tăng Chat", description: "Tăng tin nhắn chat trong live." },
      { title: "Tăng Clips View", description: "Tăng lượt xem clips." },
      { title: "Tăng Subscribers", description: "Tăng subscriber kênh." },
    ],
  },
  {
    key: "soundcloud",
    name: "SoundCloud",
    description: "Hỗ trợ tăng trưởng cho track và hồ sơ nghệ sĩ.",
    longDescription: "Tăng plays, followers, likes và reposts SoundCloud cho track và hồ sơ nghệ sĩ của bạn.",
    services: ["Plays", "Followers", "Likes"],
    accent: "#FF5500",
    keywords: [
      { title: "Tăng Plays", description: "Tăng lượt nghe cho track." },
      { title: "Tăng Followers", description: "Tăng người theo dõi SoundCloud." },
      { title: "Tăng Likes", description: "Tăng lượt thích cho track." },
      { title: "Tăng Reposts", description: "Tăng lượt đăng lại track." },
      { title: "Tăng Comments", description: "Thêm bình luận cho track." },
    ],
  },
];

export const platformsEn: PlatformItem[] = [
  {
    key: "facebook",
    name: "Facebook",
    description: "Support for page, profile and content growth.",
    longDescription: "Grow Facebook page likes, followers, post engagement, video views and reactions from one dashboard. Facebook remains one of the most widely used platforms for businesses and communities.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#1877F2",
    keywords: [
      { title: "Buy Facebook Page Likes", description: "Grow your page audience for increased reach." },
      { title: "Buy Facebook Followers", description: "Grow your Facebook follower count." },
      { title: "Buy Facebook Video Views", description: "Boost video content visibility." },
      { title: "Buy Facebook Reactions", description: "Get diverse reactions (Love, Haha, Wow)." },
      { title: "Buy Facebook Shares", description: "Increase post reach and virality." },
    ],
  },
  {
    key: "instagram",
    name: "Instagram",
    description: "Support for profile, post and reels growth.",
    longDescription: "Grow your Instagram profile with followers, likes, views, comments and story engagement delivered through one dashboard.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#E1306C",
    keywords: [
      { title: "Buy Instagram Followers", description: "Increase your Instagram follower count." },
      { title: "Buy Instagram Likes", description: "Boost likes on photos, reels and carousels." },
      { title: "Buy Instagram Views", description: "Boost views on videos and Reels." },
      { title: "Buy Instagram Comments", description: "Add comments to posts and reels." },
      { title: "Buy Instagram Story Views", description: "Drive more eyes to your daily stories." },
    ],
  },
  {
    key: "tiktok",
    name: "TikTok",
    description: "Support for channel and short-form video growth.",
    longDescription: "Grow faster on TikTok with followers, likes, views, shares and live stream engagement from a single account.",
    services: ["Followers", "Likes", "Views", "Engagement"],
    accent: "#25F4EE",
    keywords: [
      { title: "Buy TikTok Followers", description: "Grow your TikTok profile audience." },
      { title: "Buy TikTok Likes", description: "Increase engagement on posts and content." },
      { title: "Buy TikTok Views", description: "Boost visibility with more video views." },
      { title: "Buy TikTok Live Views", description: "Increase live stream viewers." },
      { title: "Buy TikTok Shares", description: "Extend reach through post distribution." },
    ],
  },
  {
    key: "youtube",
    name: "YouTube",
    description: "Support for channel and long-form video growth.",
    longDescription: "Grow your YouTube channel with subscribers, views, likes and watch hours to unlock monetisation features.",
    services: ["Subscribers", "Views", "Likes"],
    accent: "#FF0000",
    keywords: [
      { title: "Buy YouTube Subscribers", description: "Increase channel subscriber count." },
      { title: "Buy YouTube Views", description: "Boost video view count." },
      { title: "Buy YouTube Likes", description: "Increase likes on videos." },
      { title: "Buy YouTube Watch Hours", description: "Reach monetisation requirements faster." },
      { title: "Buy YouTube Comments", description: "Add comments to videos." },
    ],
  },
  {
    key: "telegram",
    name: "Telegram",
    description: "Support for channel and community group growth.",
    longDescription: "Grow your Telegram channel and community group with members, views and reactions.",
    services: ["Members", "Views", "Reactions"],
    accent: "#26A5E4",
    keywords: [
      { title: "Buy Telegram Channel Members", description: "Grow your Telegram channel audience." },
      { title: "Buy Telegram Group Members", description: "Increase group chat members." },
      { title: "Buy Telegram Post Views", description: "Boost views on channel posts." },
      { title: "Buy Telegram Reactions", description: "Add reactions to your posts." },
      { title: "Buy Telegram Shares", description: "Increase post shares." },
    ],
  },
  {
    key: "x",
    name: "X",
    description: "Support for profile and post growth.",
    longDescription: "Grow your X (Twitter) profile with followers, likes, retweets and post views.",
    services: ["Followers", "Likes", "Views"],
    accent: "#e7e9ea",
    keywords: [
      { title: "Buy X Followers", description: "Grow your X follower count." },
      { title: "Buy X Likes", description: "Increase likes on tweets." },
      { title: "Buy X Retweets", description: "Boost retweet count." },
      { title: "Buy X Views", description: "Increase tweet impressions." },
      { title: "Buy X Comments", description: "Add replies to your posts." },
    ],
  },
  {
    key: "threads",
    name: "Threads",
    description: "Support for profile and text content growth.",
    longDescription: "Grow your Threads presence with followers, likes and views on Meta's newest social platform.",
    services: ["Followers", "Likes", "Views"],
    accent: "#e7e9ea",
    keywords: [
      { title: "Buy Threads Followers", description: "Grow your Threads profile." },
      { title: "Buy Threads Likes", description: "Increase likes on posts." },
      { title: "Buy Threads Views", description: "Boost content visibility." },
      { title: "Buy Threads Replies", description: "Increase replies on posts." },
      { title: "Buy Threads Reposts", description: "Boost repost count." },
    ],
  },
  {
    key: "spotify",
    name: "Spotify",
    description: "Support for artists, playlists and audio content.",
    longDescription: "Grow your Spotify artist profile with plays, followers and playlist placements.",
    services: ["Plays", "Followers", "Playlist"],
    accent: "#1DB954",
    keywords: [
      { title: "Buy Spotify Plays", description: "Increase track play count." },
      { title: "Buy Spotify Followers", description: "Grow your artist follower count." },
      { title: "Buy Spotify Playlist Placement", description: "Get tracks added to playlists." },
      { title: "Buy Spotify Monthly Listeners", description: "Increase monthly listener count." },
      { title: "Buy Spotify Saves", description: "Increase track saves." },
    ],
  },
  {
    key: "linkedin",
    name: "LinkedIn",
    description: "Support for personal profiles and company pages.",
    longDescription: "Grow your LinkedIn presence with followers, likes, comments and profile views for individuals and businesses.",
    services: ["Followers", "Likes", "Views"],
    accent: "#0A66C2",
    keywords: [
      { title: "Buy LinkedIn Profile Followers", description: "Grow connections and profile followers." },
      { title: "Buy LinkedIn Company Followers", description: "Increase company page followers." },
      { title: "Buy LinkedIn Post Likes", description: "Boost likes on professional posts." },
      { title: "Buy LinkedIn Comments", description: "Add comments to your posts." },
      { title: "Buy LinkedIn Profile Views", description: "Increase profile visibility." },
    ],
  },
  {
    key: "pinterest",
    name: "Pinterest",
    description: "Support for pins, boards and profile growth.",
    longDescription: "Grow your Pinterest presence with followers, saves, views and clicks on pins and boards.",
    services: ["Followers", "Saves", "Views"],
    accent: "#E60023",
    keywords: [
      { title: "Buy Pinterest Followers", description: "Grow your Pinterest audience." },
      { title: "Buy Pinterest Saves", description: "Increase pin save count." },
      { title: "Buy Pinterest Views", description: "Boost pin impressions." },
      { title: "Buy Pinterest Clicks", description: "Increase outbound clicks on pins." },
      { title: "Buy Pinterest Comments", description: "Add comments to pins." },
    ],
  },
  {
    key: "snapchat",
    name: "Snapchat",
    description: "Support for profile, story and spotlight growth.",
    longDescription: "Grow Snapchat followers, story views and engagement for personal profiles and spotlight content.",
    services: ["Followers", "Views", "Engagement"],
    accent: "#FFFC00",
    keywords: [
      { title: "Buy Snapchat Followers", description: "Grow your Snapchat follower count." },
      { title: "Buy Snapchat Story Views", description: "Increase story view count." },
      { title: "Buy Snapchat Spotlight Views", description: "Boost spotlight video views." },
      { title: "Buy Snapchat Score", description: "Increase your Snap Score." },
      { title: "Buy Snapchat Shares", description: "Increase story shares." },
    ],
  },
  {
    key: "reddit",
    name: "Reddit",
    description: "Support for subreddit and post growth.",
    longDescription: "Grow your subreddit and posts with members, upvotes, comments and post views.",
    services: ["Members", "Upvotes", "Views"],
    accent: "#FF4500",
    keywords: [
      { title: "Buy Reddit Members", description: "Grow your subreddit community." },
      { title: "Buy Reddit Upvotes", description: "Boost post upvote count." },
      { title: "Buy Reddit Comments", description: "Add comments to your posts." },
      { title: "Buy Reddit Post Views", description: "Increase post impressions." },
      { title: "Buy Reddit Karma", description: "Increase account karma." },
    ],
  },
  {
    key: "discord",
    name: "Discord",
    description: "Support for server and community growth.",
    longDescription: "Grow your Discord server with members, reactions and online users for a thriving community.",
    services: ["Members", "Reactions", "Online"],
    accent: "#5865F2",
    keywords: [
      { title: "Buy Discord Server Members", description: "Grow your Discord community." },
      { title: "Buy Discord Online Users", description: "Boost online member count." },
      { title: "Buy Discord Reactions", description: "Increase message reactions." },
      { title: "Buy Discord Voice Users", description: "Boost voice channel activity." },
      { title: "Buy Discord Server Boosts", description: "Add server boost level." },
    ],
  },
  {
    key: "twitch",
    name: "Twitch",
    description: "Support for channel and live stream growth.",
    longDescription: "Grow your Twitch channel with followers, live viewers and chat engagement for your streams.",
    services: ["Followers", "Views", "Engagement"],
    accent: "#9146FF",
    keywords: [
      { title: "Buy Twitch Followers", description: "Grow your Twitch channel audience." },
      { title: "Buy Twitch Live Viewers", description: "Boost live stream viewer count." },
      { title: "Buy Twitch Chat Messages", description: "Increase chat activity in live streams." },
      { title: "Buy Twitch Clip Views", description: "Boost clip view count." },
      { title: "Buy Twitch Subscribers", description: "Grow channel subscriber count." },
    ],
  },
  {
    key: "soundcloud",
    name: "SoundCloud",
    description: "Support for tracks and artist profile growth.",
    longDescription: "Grow your SoundCloud presence with plays, followers, likes and reposts on tracks.",
    services: ["Plays", "Followers", "Likes"],
    accent: "#FF5500",
    keywords: [
      { title: "Buy SoundCloud Plays", description: "Increase track play count." },
      { title: "Buy SoundCloud Followers", description: "Grow your SoundCloud profile." },
      { title: "Buy SoundCloud Likes", description: "Increase likes on tracks." },
      { title: "Buy SoundCloud Reposts", description: "Boost track reposts." },
      { title: "Buy SoundCloud Comments", description: "Add comments to tracks." },
    ],
  },
];
